# These are supported funding model platforms

github:
  - AbhiVarde 
patreon: 
open_collective: 
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: 
thanks_dev: 
custom:
  - "https://abhivarde.gumroad.com/l/portfolio-template-syncui"
  - "https://abhivarde.gumroad.com/l/saas-template-syncui"
